#!/bin/bash
# -----------------------------------------------------------------------------
# Directly_Discretizing_Tensor_Computation-DDTC - Start Application
#
# Author:    Johannes Gebert »gebert@hlrs.de«
# Created:   24.11.2021
# Last edit: 24.11.2021
# ------------------------------------------------------------------------------
#PBS -N DDTC
#PBS -l select=1:node_type=rome:mpiprocs=3
#PBS -l walltime=00:10:00
#
# Change to the direcotry that the job was submitted from
cd $PBS_O_WORKDIR
#
# Load env
source ./setenv.sh hawk --no-output 
#
# ------------------------------------------------------------------------------
# Define an output file containing the std_out of the program. Currently, it 
# only concerns Metis and Petsc. All other std_out is redirected into the new
# std_out file. 
#
NEW_BSNM_FEATURE=Tensors
NEW_BSNM_PURPOSE=Pro    
NEW_APP_NAME=DDTC
#
MAKESHIFT_STD_OUT=$PWD/datasets/SC00-0_tc_$NEW_BSNM_PURPOSE"_"$NEW_APP_NAME"_"$NEW_BSNM_FEATURE".metis_petsc-std_out"
# ------------------------------------------------------------------------------
#
# Launch the parallel mpi application (compiled with intel mpi) to the allocated compute nodes
mpirun -n 3 bin/ddtc_v1.0.0_x86_64 $PWD/datasets/SC00-0_tc_Dev_BinDecomp_isotropic-HEX08.meta > $MAKESHIFT_STD_OUT