#!/bin/bash
# -----------------------------------------------------------------------------
# Directly_Discretizing_Tensor_Computation-DDTC - Start Application
#
# Author:    Johannes Gebert »gebert@hlrs.de«
# Created:   22.11.2021
# Last edit: 22.11.2021
# ------------------------------------------------------------------------------
#PBS -N DDTC
#PBS -l select=1:node_type=clx384gb40c:mpiprocs=3
#PBS -l walltime=00:10:00
#
# Change to the direcotry that the job was submitted from
cd $PBS_O_WORKDIR
#
# Load env
source ./setenv.sh vulcan
#
# Launch the parallel mpi application (compiled with intel mpi) to the allocated compute nodes
mpirun -n 3 bin/ddtc_v1.0.0_x86_64 $PWD/datasets/SC00-0_tc_Dev_DDTC_isotropic-HEX08.meta